### ISSUE TITLE
Variable Missmatch

### ISSUE THREAD

**Issue by aschaber1** [nmcclain/formbricks-helm#2]
Hello,

I tried to install the helm chart and stumbled across the storageclass which isn't set when I adapted the `values.yaml`.

At a closer look I noticed that there is a mismatch between the 
`values.yaml`: `storageClassName`
`storage.yaml`: `{{ .Values.persistence.storageClass }}`

Please consider aligning the variable names.

Best regards
Alexander

- https://github.com/nmcclain/formbricks-helm/blob/c21567ef3b1adc85bb204450ac372967b4fe4540/formbricks/templates/storage.yaml#L13
- https://github.com/nmcclain/formbricks-helm/blob/c21567ef3b1adc85bb204450ac372967b4fe4540/formbricks/values.yaml#L225

**Comment by nmcclain** [comment]
Fixed - THANK YOU!
